### ISSUE TITLE
Build fails while running command : 'ng build --prod'

### ISSUE THREAD

**Issue by vishal-variyani** [SaturnTeam/saturn-datepicker#138]
I am getting this error when I try to create a production build.:

`ERROR in ./node_modules/saturn-datepicker/fesm2015/saturn-datepicker.js Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js): TypeError: Cannot read property 'kind' of undefined at isAngularDecoratorMetadataExpression (/home/codal/projects/altumai-fe/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:230:35) at checkNodeForDecorators (/home/codal/projects/altumai-fe/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:53:21)`

**Comment by florent1933** [comment]
@vishal-variyani , I have the same issue. Did you manage it?

**Comment by Lempkin** [comment]
Hi! Same here, did you find any solution?

**Comment by rickyh2007** [comment]
Same here, any solution to it or workaround?

**Comment by nschimek** [comment]
I am also getting this in Angular 8.  Disabling the build optimizer in angular.json worked as a temporary workaround.  

According to https://stackoverflow.com/questions/58694820/cannot-read-property-kind-of-undefined, the solution looks pretty simple?  But requires changing tsconfig.json.

**Comment by andgest** [comment]
Same problem here

**Comment by lucifer63** [comment]
The problem still exists
